### PR TITLE
Set up Travis CI and Codecov integration

### PR DESCRIPTION
**Pull request by alex-konovalov**
This PR adds sets up for continuous integration and code coverage reports using Travis CI and Codecov. With it, it will be possible to automatically test each commit, and tests pull requests before being merged.

At the moment, please see tests results under my account:
- https://travis-ci.org/github/alex-konovalov/simple_network_sim
- https://codecov.io/gh/alex-konovalov/simple_network_sim/branch/setup-ci 

After merging this PR, and configuring Travis CI integration, it will be possible to see them for _this_ repository. I will then add badges to the README file to display tests status.

### CODE REVIEW

**Comment by aflag** [comment]
I think we may have had a bit of overlapping in this task, unfortunately: https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/114

**Comment by alex-konovalov** [comment]
@aflag ah, nice - I was pointed to this repo initially, and haven't seen this among currently open PRs. Good to know that this already taken care of. I will be happy to help if I can.

**Comment by bobturneruk** [comment]
Hi @alex-konovalov! Great to have your contribution here - and your specific expertise in this area on the team - can you have a look at https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/114 and see what you think, particularly on the GitHub vs. Travis question. I'll drop you an email about getting onboard with the team.

**Comment by alex-konovalov** [comment]
Closed in favour of #26.

**Pull request closed without merging**
