### PR TITLE
Issue 507

### PR DESCRIPTION
**Pull request by anthonyohare**
Download the data (excel spreadsheets) from NRS and transform them into row based population estimates used by simple_network_sim.

Doesn't change any code, when the script is run it will download the data to a subdirectory (that is added to .gitignore), transform it and save it to a file called hb2019_pop_est.csv so it doesn't directly affect the data pipeline

### CODE REVIEW

**Comment by aflag** [comment]
Isn't this information already retrieved from https://github.com/ScottishCovidResponse/SCRCdata/blob/master/inst/scripts/nrs_demographics.R?

**Comment by bobturneruk** [comment]
@anthonyohare thanks for putting this up and sorry if you've ended up working on something that's also happening elsewhere in the consortium! If you or @aflag (or anyone) are able to confirm if there's duplication here, that would be great.

**Comment by aflag** [comment]
@bobturneruk you can look at the data they have onborded already here: ftp://boydorr.gla.ac.uk/scrc/human/demographics/scotland/data/demographics.h5 I believe /hb/1year/{male,female}/array should give us what we need. There will need a bit of processing to get into the format our model expects, but no need to parse excel files. I see a HB id in the demographics.h5, which I think all the dicts are used to create in the end, I may be wrong about that one though.

**Comment by bobturneruk** [comment]
I'll have a look but @magicicada or @anthonyohare may give a better, faster answer?

**Comment by aflag** [comment]
btw, the tool that ended up working for me was HDFCompass (https://support.hdfgroup.org/projects/compass/index.html) it's not perfect, but it works. I think hdfview is more popular, but I couldn't open the consortium files with it for some reason.

**Comment by bobturneruk** [comment]
Cheers. Can't get boydorr.gla.ac.uk to respond at present.

**Comment by anthonyohare** [comment]
duplication of work done elsewhere.

**Pull request closed without merging**
