### PR TITLE
Cleanup notebooks & add notebook with custom usage

### PR DESCRIPTION
**Pull request by FiodorG**

### CODE REVIEW

**Comment by FiodorG** [comment]
Tracking https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/609

**Comment by magicicada** [comment]
Why the changes to the .h5 compartment-transition file - just incidental?  

Otherwise things look uncontroversial to me.

**Review by magicicada — APPROVED** [review]
My only question is about the change to the .h5 file - why the change?  Subject to that, looks fine to me.

**Comment by FiodorG** [comment]
Thanks @magicicada 

I have a few things left to do before merging (including that famous notebook with custom inputs).

The change on the hdf5 file is required, it seems that before it was wrongly populated with many empty columns, this is cleaning it up (but not changing the numbers)

**Pull request merged**
