### PR TITLE
Use new regression infrastructure in all tests

### PR DESCRIPTION
**Pull request by aflag**
One of the problems we were having was that the regression tests were difficult to update. Now if they fail, you delete the backing file and run the test again. A new file will be created and you can then manually check that it looks ok. If everything looks good, you can commit the new file and the test will be passing.

### CODE REVIEW

**Comment by magicicada** [comment]
Given my fun and games updating the tests recently, I approve of this idea!  Two things: 
1. Could we include a bit of text on how to update these somewhere so that I can refer back to it when I have to do it?
2. Because I'm only learning about how this sort of testing works, I'd love a quick review from @bobturneruk or @alex-konovalov

**Comment by aflag** [comment]
@magicicada the explanation on how this work was added here: https://github.com/ScottishCovidResponse/simple_network_sim/blob/5c1b086b6c43cc1e04ce506968a05b733902ee00/tests/utils.py I think @bobturneruk liked the idea (which I introduced in the previous PR), so that's why I'm proposing adopting it to all regression tests. However, I agree that it's not easy to find it like that. Maybe I should add a `CONTRIBUTING` section in the readme explaining this. What do you think?

**Comment by bobturneruk** [comment]
I guess the potential downside of the approach is that someone could naively run the tests twice and have them always pass? However, my understanding is that this can't happen with the CI as a new container is made each time the tests are run (and we see all test data changed on a branch in review). And this allows the expected test results to be updated with changing definitions of "correct output" (which does change as we add features and we need to keep an eye on). Please correct me if I'm wrong on any of this!

I think we should bring in these changes (although I'd previously thought we were just talking about the images, my bad). I think, as @aflag says, it would be good to have a brief explanation of this under "Testing" in the readme. I hope to [expose the more detailed docstring via readthedocs](https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/113).

**Comment by aflag** [comment]
@bobturneruk unless you delete the baseline file, the test will never pass. Running it twice will only work when you don't have a baseline to begin with. So, if someone gets the test to pass, they must consciently have changed the baseline file and it should be clear in the PR that the file was altered. I think it'd be nice if there was some way to automatically add a tag or some other notification to PRs that make changes to regression test data. I haven't investigated how to do that though.

**Pull request merged**
