### PR TITLE
Split simulation code into modules

### PR DESCRIPTION
**Pull request by aflag**
I've took the liberty of creating also the common module with some generic functions that may be used by different modules. We can split that into more modules (or make it into a package) later if it starts to grow.

This PR also includes new unit tests on the network_of_populations. They are all passing. The coverage report I got is evidence that the split was done correctly. Also, based on that report, I've tagged a few other functions as "NotCurrentlyInUse": `basicReportingFunction`, `doSetupAgeStruct` and `nodeUpdate`.

I've tried to import all the modules required by network_of_individuals, but I couldn't find where `fromStateTrans` comes from, so I left it unresolved.

image

### CODE REVIEW

**Comment by bobturneruk** [comment]
I notice this PR also adds more unit tests.

**Comment by bobturneruk** [comment]
Or does it just move them around?

**Comment by magicicada** [comment]
I have no objection to what I've seen, but won't have time to properly review until quite. abit later today.  @bobturneruk if you can do the review needed here for @aflag please go ahead

**Comment by bobturneruk** [comment]
I think splitting things up into modules is great - the specifics of the splits I'm happy with if they make sense to @aflag (of course they do!) and to @magicicada. This will make the project easier to understand. I will likely raise an issue for module-level documentation. I've not looked at the individual tests in detail but I'm happy that we have more test coverage. Tests can be adjusted as functionality changes.

@aflag - I'd be inclined to wait for an approving review from @magicicada as this is somewhat strategic.

**Comment by aflag** [comment]
I can wait for @magicicada. Will she be able to merge it herself? My main concern is not to block her for the work she has planned.

**Pull request merged**
