### PR TITLE
Add model documentation

### PR DESCRIPTION
**Pull request by FiodorG**
Adding model documentation written by @magicicada and the inference section.

### CODE REVIEW

**Comment by bobturneruk** [comment]
Does this supersede https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/model_overview_simple_network_sim.md ?

**Comment by bobturneruk** [comment]
Having a few difficulties building a pdf from this - @FiodorG please can you share the command you used to build?

**Comment by FiodorG** [comment]
> Does this supersede https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/model_overview_simple_network_sim.md ?

My opinion is that yes, the .tex document should be much as detailed as we can be, both on the model working and the inference. But it's always nice to have a tldr on the main page of github. But this is just an opinion

**Comment by FiodorG** [comment]
> Having a few difficulties building a pdf from this - @FiodorG please can you share the command you used to build?

@bobturneruk No special commands, I tool the latest installs of miktex and texmaker from the official websites yesterday, and it "just works" for me. What error message do you get?

**Comment by anthonyohare** [comment]
It compiles fine with pdflatex but not so with plain latex because it can't deal with the jpegs.
e.g.
Cannot determine size of graphic in images/compartments.jpg (no BoundingBox)
Hope this helps...

**Comment by bobturneruk** [comment]
> > Does this supersede https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/model_overview_simple_network_sim.md ?
> 
> My opinion is that yes, the .tex document should be much as detailed as we can be, both on the model working and the inference. But it's always nice to have a tldr on the main page of github. But this is just an opinion

I think we should drop `model_overview_simple_network_sim.md` as part of this PR as it will make maintenance easier.

**Comment by FiodorG** [comment]
> It compiles fine with pdflatex but not so with plain latex because it can't deal with the jpegs.
> e.g.
> Cannot determine size of graphic in images/compartments.jpg (no BoundingBox)
> Hope this helps...

Ah I see, thanks for checking this. Do you think it will be better with another figure format (png for example?)

**Comment by FiodorG** [comment]
> > > Does this supersede https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/model_overview_simple_network_sim.md ?
> > 
> > 
> > My opinion is that yes, the .tex document should be much as detailed as we can be, both on the model working and the inference. But it's always nice to have a tldr on the main page of github. But this is just an opinion
> 
> I think we should drop `model_overview_simple_network_sim.md` as part of this PR as it will make maintenance easier.

Ok sure, completely delete it?

**Comment by bobturneruk** [comment]
I think so, or if any bits of it are useful add them to the .tex, and update links in readme. Unless @magicicada disagrees. Also my pdf build problems were me+windows+powershell+miktex. That said, a brief markdown or text file giving instructions on how to build e.g. download some tex distro, run pdflatex, open pdf would be useful - not everyone who wants to look at this will be latex savvy. Ultimately I'd like to have the pdf build as part of CI, but this ain't happening this week.

**Comment by anthonyohare** [comment]
@FiodorG - I normally go for png as the quality is usually better but I don't think it will matter too much for the plots in this doc

**Comment by magicicada** [comment]
> I think so, or if any bits of it are useful add them to the .tex, and update links in readme. Unless @magicicada disagrees. 

I agree, remove it.

**Comment by bobturneruk** [comment]
I'm having a look at the moment, although once it hits the ABC-SMC I think I understand it well enough to comment. Could one of the other modellers from the consortium be called upon for an opinion? Rikiya?

**Comment by magicicada** [comment]
> I think so, or if any bits of it are useful add them to the .tex, and update links in readme. Unless @magicicada disagrees. Also my pdf build problems were me+windows+powershell+miktex. That said, a brief markdown or text file giving instructions on how to build e.g. download some tex distro, run pdflatex, open pdf would be useful - not everyone who wants to look at this will be latex savvy. Ultimately I'd like to have the pdf build as part of CI, but this ain't happening this week.

If it's a priority to have it immediately readable,

> I'm having a look at the moment, although once it hits the ABC-SMC I think I understand it well enough to comment. Could one of the other modellers from the consortium be called upon for an opinion? Rikiya?

@anthonyohare knows enough about ABC-SMC in general to be potentially useful

**Comment by anthonyohare** [comment]
> > I'm having a look at the moment, although once it hits the ABC-SMC I think I understand it well enough to comment. Could one of the other modellers from the consortium be called upon for an opinion? Rikiya?
> 
> @anthonyohare knows enough about ABC-SMC in general to be potentially useful

I can do it now but happy for it to be merged if under time pressure and for issues to be raised afterwards.

**Comment by bobturneruk** [comment]
Thanks @anthonyohare. You're likely delighted to be "potentially useful" 😄 ! Not sure if the "can" should be a "can't". Could you look at it and we aim to merge Friday pm?

**Comment by magicicada** [comment]
> Thanks @anthonyohare. You're likely delighted to be "potentially useful" 😄 ! Not sure if the "can" should be a "can't". Could you look at it and we aim to merge Friday pm?

I hope I know Ant well enough that he's not offended by the term :)

**Comment by FiodorG** [comment]
> @FiodorG - I normally go for png as the quality is usually better but I don't think it will matter too much for the plots in this doc

Thanks I replaced them to png now (it's the default output from Jupyter when I save a graph from there)

**Comment by anthonyohare** [comment]
> > Thanks @anthonyohare. You're likely delighted to be "potentially useful" 😄 ! Not sure if the "can" should be a "can't". Could you look at it and we aim to merge Friday pm?
> 
> I hope Ant and I know each other well enough that he's not offended by the term :)

@bobturneruk, I've started reading through it so I did meant 'can' but the sentence was so poorly written it sounded wrong! 

My goal in life is to be potentially useful to someone at some point!

**Comment by anthonyohare** [comment]
> > Thanks @anthonyohare. You're likely delighted to be "potentially useful" 😄 ! Not sure if the "can" should be a "can't". Could you look at it and we aim to merge Friday pm?
> 
> I hope Ant and I know each other well enough that he's not offended by the term :)

I read it without batting an eyelid

**Comment by FiodorG** [comment]
I pushed the pdf file (and deleted the prev .md file with the description). Is everyone ok to push the pdf file in the repo as well?

**Comment by anthonyohare** [comment]
I've read the ABC-SMC section and have no comments. Happy to see this merged

**Comment by magicicada** [comment]
I'm going to make some of the small changes that Bob has suggested

**Comment by FiodorG** [comment]
- Converted all to png (thanks to @magicicada)
- Removed the old markdown for model description
- Linked the latex doc in the main markdown page
- Added steps on how to generate latex file
- Review and proof-read (for typos + by other SNS team member)

Are we all ok to merge this PR?

**Pull request merged**
